### ISSUE TITLE
Error with Permissionsshop

### ISSUE THREAD

**Issue by DenDerErn** [j0ach1mmall3/PermissionsShop#12]
Error: http://pastebin.com/KAhnz0TL
Server Version: Spigot 1.8.8-R0.1-SNAPSHOT
Plugin Version: 3.1.2
Config file: only the config.yml generates, and i did not touch it
Plugins: http://imgur.com/aDfZF0H

**Comment by j0ach1mmall3** [comment]
Change your sounds to 1.8 ones

**Comment by DenDerErn** [comment]
How do i do that?

**Comment by j0ach1mmall3** [comment]
Well, just change them in the config, you can find a list of 1.8 sounds online

**Comment by DenDerErn** [comment]
I know im asking alot

But i cant get it to work, i found some sounds and i think that worked, but it wont generate the other files, and i tried copying them from the github page, but it still do not work

**Comment by j0ach1mmall3** [comment]
The github page uses 1.9 sounds
