### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NCSGeek** [j0ach1mmall3/PermissionsShop#13]
Sorry, missed the part about posting bugs here, Truly am sorry as that is one of my personal pet peeves. Anyway enough talk, this bug seems to happen on startup and reload.

Bug: http://pastebin.com/8js0WFQg

**Comment by j0ach1mmall3** [comment]
Please show me the /jdebug output

**Comment by NCSGeek** [comment]
How might i do that?

**Comment by j0ach1mmall3** [comment]
You execute the /jdebug command in the console.
You copy the relevant output link.
You paste the relevant output link

**Comment by NCSGeek** [comment]
Got It: https://gist.github.com/anonymous/c557dcaf1a1fb75862b078451a417e5d

**Comment by j0ach1mmall3** [comment]
I need the PermissionsShop debug link, not the JLib one, there should be multiple

**Comment by j0ach1mmall3** [comment]
It's probably an issue with the "ClickSound" config value

**Comment by NCSGeek** [comment]
Yeah, when looking at the error message i get, It is something to do with the clicksound in the config. And how do i get the PermShop debug link? When i do /jdebug i get the Jlib one

**Comment by j0ach1mmall3** [comment]
Then fix the clicksound in the config, it's probably an invalid one or isn't specified

**Comment by NCSGeek** [comment]
I tried changing it to other things, What is an example of one that works?

**Comment by j0ach1mmall3** [comment]
The default config works for 1.9

**Comment by NCSGeek** [comment]
Oh, I am on 1.8, Is that an issue?

**Comment by j0ach1mmall3** [comment]
Then you should change the sounds to 1.8 ones

**Comment by NCSGeek** [comment]
Can i get some sounds that work in 1.8?

**Comment by j0ach1mmall3** [comment]
There's a list somewhere online, google
