### ISSUE TITLE
Plugin creates config file but nothing else.

### ISSUE THREAD

**Issue by Terryjomjerry** [j0ach1mmall3/PermissionsShop#16]
Here is the error in console, I'm on 1.8.6 fyi.

http://pastebin.com/bzJEKV0e

And here is a list of the plugins I have, some may interfere idk.

AlwaysDay-v2.2.8
BungeePortals
ChestCommands
Citizens
CommandNPC
CraftBook
CreateYourOwnMenus-0.5.9
CustomEnchantments
CustomJoinItems
Essentials
EssentialsChat
EssentialsProtect
EssentialsSpawn
HolographicDisplays
HolographicDisplaysPatch
hub
**JLib**
KitAdder
LaunchOnCOmmand
Magic-5.3.3
Multiverse-Core-2.4
Multiverse-Inventories
Multiverse-Portals
Parachute
PermissionsEx-1.2.3.4
**PermissionsShop**
SimpleGrapple
SonezSpawn
Thrower
**Vault**
VoidSpawn
WorldEdit
worldguard-6.1.2
worldguard-6.1
WorldReset

Don't mind the double worldguard. I'll fix that.

Anyways I am not sure what the error is. I have the latest version available of Permissions Shop. Hit me up, thanks!

**Comment by j0ach1mmall3** [comment]
You need to upgrade/downgrade the sounds

**Comment by Terryjomjerry** [comment]
Okay I'm not sure what you mean. I used note.pling instead of the other sounds in the original config in the example above.

**Comment by j0ach1mmall3** [comment]
That's not a valid sound, use NOTE_PLING
I don't understand how you can come up with note.pling...

**Comment by Terryjomjerry** [comment]
I used note.pling because that is what is used when using the command /playsound

**Comment by Terryjomjerry** [comment]
Thanks by the way.
