### ISSUE TITLE
Permission Shop price Error

### ISSUE THREAD

**Issue by DuckCraftPvP** [j0ach1mmall3/PermissionsShop#17]
When i set the shop prices to over a mil it shows as say 5mil 5e7

**Comment by j0ach1mmall3** [comment]
I can't fix that

**Comment by DuckCraftPvP** [comment]
Troll, You should be able to as ur the dev goof.

**Comment by j0ach1mmall3** [comment]
Yea ofcourse I can. Let me restate: I don't want to spend time and resources into fixing that

**Comment by DuckCraftPvP** [comment]
Not a good example of a developer, Ima pretend i did not hear that for ur sake.

**Comment by j0ach1mmall3** [comment]
I provide this resource for free. I provide this (limited) support for free. And now you're going to state me what to do? I'd rather you just shut up and use my resource how you want, or don't use it. I am in no way an example to anyone, and I don't have to be. If you have any more unrelated issues, you can create a new one
