### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by taperpaper** [j0ach1mmall3/PermissionsShop#18]
I was wondering if there you could support multiple currencies for this plugin? It is an awesome plugin and is exactly what I need, but I want to be able to use a spectate currency; say every time someone votes they get a certain amount of "tokens" (which is a separate currency from main dollars) it would be fantastic if they could spend these "tokens" on things in the shop
I don't know how hard it would be to implement, but it would be so incredible if you could get something like that working. I don't know what would be easier, but even if you used dummy scoreboards points that would work. I just need an isolated currency separate from the default, that I can use for my vote shop.
Thank you for your time!

**Comment by j0ach1mmall3** [comment]
I won't implement anything other than vault
