### ISSUE TITLE
Can't Buy Anything

### ISSUE THREAD

**Issue by jianluca1** [j0ach1mmall3/PermissionsShop#2]
Help! I can't buy anything. Here is whet the console says:

07.11 17:31:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
07.11 17:31:54 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
07.11 17:31:54 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
07.11 17:31:54 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
07.11 17:31:54 [Server] INFO at com.j0ach1mmall3.permissionsshop.listeners.PlayerListener.onInventoryClick(PlayerListener.java:119) ~[?:?]
07.11 17:31:54 [Server] INFO at com.j0ach1mmall3.permissionsshop.listeners.PlayerListener.handlePurchase(PlayerListener.java:176) ~[?:?]
07.11 17:31:54 [Server] INFO at com.j0ach1mmall3.jlib.inventory.GUI.<init>(GUI.java:40) ~[?:?]
07.11 17:31:54 [Server] INFO at com.j0ach1mmall3.jlib.inventory.GUI.<init>(GUI.java:30) ~[?:?]
07.11 17:31:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.inventory.CraftInventory.addItem(CraftInventory.java:267) ~[craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at org.apache.commons.lang.Validate.noNullElements(Validate.java:364) ~[craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO Caused by: java.lang.IllegalArgumentException: Item cannot be null
07.11 17:31:54 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
07.11 17:31:54 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
07.11 17:31:54 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
07.11 17:31:54 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1521) [craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit.jar:git-Bukkit-33d5de3]
07.11 17:31:54 [Server] INFO org.bukkit.event.EventException
07.11 17:31:54 [Server] ERROR Could not pass event InventoryClickEvent to PermissionsShop v2.1.4

**Comment by j0ach1mmall3** [comment]
I will see what I can do about this, show me your configs please

**Comment by jianluca1** [comment]
I tried re downloading the plugin at the latest version, and it still kept doing the same error message. I then switched to an earlier version, and now the plugin is working properly.

**Comment by j0ach1mmall3** [comment]
Will be fixed in the newest version.
