### ISSUE TITLE
Error when trying to by something.

### ISSUE THREAD

**Issue by jeepingviini** [j0ach1mmall3/PermissionsShop#5]
I get error when I'm trying to buy some thing.

Error: http://pastebin.com/UJHBFftC

Here are plugins cofigs.
Configs: 
Config.yml http://pastebin.com/yhUMVPZk
Discounts.yml http://pastebin.com/2edWNks0
Lang.yml http://pastebin.com/Per1RF34
Sales.yml http://pastebin.com/wTis68Lt
Shops.yml http://pastebin.com/9QJMzjfB

Thanks.

Ps. I use pastbin because I think it's easier to read that way.

**Comment by j0ach1mmall3** [comment]
Weird, doesn't seem that anything is wrong. What have you changed to the config files?

**Comment by jeepingviini** [comment]
Nothing big i think Shop name and stuff and in config.yml removed account that money goes to

**Comment by j0ach1mmall3** [comment]
I will see if I can fix this in PermissionsShop 3.0.0 but it'll probably take a long time before it comes out

**Comment by jeepingviini** [comment]
Ok

**Comment by xXAndrew28Xx** [comment]
Same thing for me.
