### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Babyloutie** [j0ach1mmall3/PermissionsShop#6]
Well... I don't know if it's a bug or not, but is there a possibility to get a category in a category? If it's not a bug, could you please try to add this feature? :D 

Thanks for your time and reply ;)

**Comment by j0ach1mmall3** [comment]
It's not possible ATM, but I'll see what I can do about it in 3.0.0

**Comment by Babyloutie** [comment]
Awesome! Thanks :D
